### ISSUE TITLE
How to tab between input fields

### ISSUE THREAD

**Issue by dasheck0** [orange-games/phaser-input#12]
Hi,

I was just playing around with the library and was wondering how to implement tab between two input fields. Here is some code of mine (which does not work):

```
var tabKey = this.game.input.keyboard.addKey(Phaser.Keyboard.TAB);
            tabKey.onDown.add(this.focusNextInput, this);
```

```
focusNextInput: function () {
            console.log("Tab hit");
            if (this.currentFocus > -1) {
                var temp = [this.emailInput, this.passwordInput];
                temp[this.currentFocus].endFocus();

                this.currentFocus += 1;
                if (this.currentFocus >= temp.length) {
                    this.currentFocus = 0;
                }

                temp[this.currentFocus].startFocus();
            }
        }
````

The first tab does work and selects the input field but subsequent tabs do not work. They focus the browsers native buttons (back, reload button, etc...). Can anyone help?

EDIT: Also the debug log message is only printed on the first tab hit.

Best regards
dasheck

**Comment by dasheck0** [comment]
I did a little more research. In a minimum working example (not including phaser-input) the above code does work. So I commented the method focusNextInput() out line by line and found that the line 
```
temp[this.currentFocus].startFocus();
```
is causing the trouble. So I digged into the code and suspect that this method is responsible for this InputField.js:262:
```
        private keyUpProcessor():void {
            this.domElement.addKeyUpListener(this.keyListener.bind(this));
            this.domElement.focus();
            
            if(this.blockInput === true) {
                this.domElement.blockKeyDownEvents();
            }
        }
```

**Comment by AleBles** [comment]
Yes, there's a reason for this. Phaser-Input blocks all phaser handled key events so that none of them would interfere when you are typing something. You can override this by setting blockInput to false for the inputField:
```javascript
            var user = game.add.inputField(game.width / 2 - 85, 180 - 17, {
                font: '18px Arial',
                fill: '#212121',
                fillAlpha: 0,
                fontWeight: 'bold',
                width: 150,
                max: 20,
                padding: 8,
                borderWidth: 1,
                borderColor: '#000',
                borderRadius: 6,
                placeHolder: 'Username',
                textAlign: 'center'
            });
            user.blockInput = false;
```
if this 'work-around' is not enough for you we could have a look at other solutions

**Comment by dasheck0** [comment]
Unfortunately this does not change the described behaviour. I set blockInput to false for all of the input fields. But as soon as I press tab it switches to the browser keys. The only difference is that it happens at the first tab as well.

**Comment by AleBles** [comment]
'work-around' was between quotes for a reason :p. We designed it to be like this because we think blocking all game related input when an input active is wanted. You might use some keyboard hotkeys for your menu's for example, and you don't want them to be triggered when you are typing something in the input field.

The readme does mention this @ https://github.com/orange-games/phaser-input#capture-input-events but I can get that it's not very clear, also there is no mention of it in the example, so we could update that.

Your issue however is still a valid thing because default browser behaviour for tab on input is to switch to the next element, but canvas (and phaser) is not aware of any of these elements. We could offcourse make an exception for Tab (which I'm tempted to do, because we already have exceptions for enter) but I'd like to ponder/discuss about this a bit more :)

**Comment by dasheck0** [comment]
Ah I see. The thing with the game hotkeys is indeed an issue. Also the readme does say something about this. However even if I read that (which I didn't :P) I wouldn't be able to resolve this. But this might be just me :D I highly recommend to add this snippet somewhere (either readme or wiki), since this is a common feature you know from classic HTML based input fields.
